### ISSUE TITLE
Build fails via cargo install --path . on windows

### ISSUE THREAD

**Issue by Tomok** [jamesmunns/frauth#10]
When triing to built as described in the README (clone repository, call cargo install --path .), the build fails with the following message:
error: failed to read `[..]\frauth\vendor\ed25519-dalek\Cargo.toml`

Caused by:
  Das System kann die angegebene Datei nicht finden. (os error 2)

Which translates to the sytem not being able to find the file "frauth\vendor\ed25519-dalek\Cargo.toml`"

**Comment by jamesmunns** [comment]
Ah, good call! You would need to do a `git submodule update --recursive --init` in the repo, or a `git clone --recursive`. I added a submodule at the last minute.

Thanks for the report! I'll try and fix this tonight, or feel free to PR a change to the README!

**Comment by jamesmunns** [comment]
Closed by #11
