### ISSUE TITLE
Add a publish date

### ISSUE THREAD

**Issue by yvrhdn** [jamesmunns/frauth#15]
Add a "publish date" or "last updated" field to the output. This field should contain a date time or timestamp.

Other people can use this field to see when the information was last updated. This will be useful to detect when people don't update their frauth identity.

**Comment by jamesmunns** [comment]
Added in the `0.2.2` release!

https://github.com/jamesmunns/frauth/commit/eca524d47c678646e0f77139dc953e6904a7c2d3
