### ISSUE TITLE
Error when publishing

### ISSUE THREAD

**Issue by fmckeogh** [jamesmunns/frauth#16]
Ran `cargo install frauth` on MacOS 10.15.2 (19C57).

I initialised with:
```
$ frauth init
Welcome to frauth!
Ready to get started? yes

It looks like you've already initialized frauth.
Do you want to re-initialize? THIS WILL ERASE YOUR EXISTING KEYS AND DATA!
Continue? yes

Creating directories...
Done.

Okay! We'll get started by collecting some required info.
What name do you want to go by?: Ferdia McKeogh

Okay, that's everything that's required. Now let's collect some optional items.

We'll now collect any identities you'd like to associate with yourself. You can add as many as you like.
These identities will be publicly visible to anyone.

Identities have a 'name', like 'twitter', 'email', 'mobile', etc.
and an 'id', like 'my_twitter_id', 'me@example.com', or '+4912345678901'.


Add/Update an identity? no

Would you like to add a public status message? You can change or add this later as well.


Add a status? no

frauth has been initialized!
```

```
$ frauth publish
Error { inner: ErrorInner { kind: Custom, line: Some(11), col: 0, at: Some(612), message: "invalid type: sequence, expected An ed25519 keypair, 64 bytes in total where the secret key is the first 32 bytes and is in unexpanded form, and the second 32 bytes is a compressed point for a public key.", key: ["keypair"] } }

Error: "Failed to parse user info!"
```

I get the exact same output with a debug build from the master branch.

**Comment by jamesmunns** [comment]
Thanks for the report! I'll try to reproduce locally and see what the issue is.

**Comment by fmckeogh** [comment]
Anything I can do to help?

**Comment by jamesmunns** [comment]
So, I wasn't able to reproduce this directly locally. But, this looks like the error I got before I switched to a patch of `ed25519-dalek`. See https://github.com/jamesmunns/frauth/blob/master/Cargo.toml#L9-L13 for some context.

I'm guessing that the crates.io install isn't respecting the workspace-level cargo patch, which is unfortunate. I'm unsure why this is only happening on mac, but I was able to reproduce it on my old laptop. You can probably verify this by making sure you have all submodules checked out in the local install (`git submodule update --init --recursive`), and see if that fixes things.

For now, I'll publish my fork of ed25519-dalek, to prevent further issues like this.

**Comment by jamesmunns** [comment]
@chocol4te I also published `v0.2.3`, could you let me know if that fixes things for you?

**Comment by jamesmunns** [comment]
Update: It doesn't, at least on my machine :(

**Comment by jamesmunns** [comment]
Okay, final update, this should be fixed as of 0.2.4. I've also gotten rid of the submodule.

**Comment by fmckeogh** [comment]
All working!

https://mckeogh.tech/me.frauth with public key `jW8UACYFq3CxwfUtpl6P7NWsaeZBNhaJr03fCzFK3pI=` :)

**Comment by jamesmunns** [comment]
@chocol4te added you! Feel free to add me back:

https://jamesmunns.com/me.frauth

pubkey: `uOoY1GxJve4AqGoioN6edJcWNrqz0orWPhY/TP/HfAQ=`

**Comment by fmckeogh** [comment]
Added and updated my published ID :)
