### ISSUE TITLE
Adding oneself as a friend

### ISSUE THREAD

**Issue by fmckeogh** [jamesmunns/frauth#17]
Unsure if this should be allowed, but I was able to successfully add myself as a friend.

**Comment by jamesmunns** [comment]
Probably not! I should add a filter for this :)

**Comment by jamesmunns** [comment]
If you're interested, you can probably add the check here, just make sure that the public key doesn't == our own public key: https://github.com/jamesmunns/frauth/blob/master/cli/src/subcmd/friend.rs#L108-L112

Here is how to load your own information, you can probably move this function to `src/util.rs`: https://github.com/jamesmunns/frauth/blob/master/cli/src/subcmd/publish.rs#L49-L57

**Comment by fmckeogh** [comment]
I’ll start on a PR :)
