### ISSUE TITLE
`frauth me` command to edit own data

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/frauth#18]
We should have a `frauth me` subcommand that should allow you to:

* `frauth me view` - Display your own data, output should be sort of like `frauth friend list`, but just for you
* `frauth me edit` - Some kind of interactive menu to allow you to edit info like:
  * `status`
  * `name`
  * `identities`
    * add new identities
    * edit identities
    * remove identities

We should probably remind users to re-publish if they have changed anything with `frauth me edit`.

Contributions welcome! I'm currently working on the discovery tools at the moment.

**Comment by jamesmunns** [comment]
CC @koenaad, I think you were asking about this!

**Comment by yvrhdn** [comment]
Yeah, that's right! 🙂 I'm willing to contribute this myself, I haven't used structopt before so this seems like a good learning opportunity.

**Comment by yvrhdn** [comment]
Design decision: should `frauth me` be interactive (similar to `frauth init`) or use flags/subcommands? (similar to `frauth friend`).

I could imagine the following commands

- `frauth me pubkey` (returns the pubkey)
- `frauth me status get` and `frauth me status set 'My new status'`
- `frauth me identity list`, `frauth me identity remove <name>`, `frauth me identity add <name> <value>`

**Comment by jamesmunns** [comment]
Hmm, that's a good question! I'm open to either option. Perhaps we could go with the interface you described (noninteractive), but maybe also have an interactive option (similar to `git add -i`) later? I could see `frauth me edit` or `frauth me interactive` or `frauth me -i` as being good choices for that.
